[package]
name = "numpy"
version = "0.15.0"
authors = [
    "The rust-numpy Project Developers",
    "PyO3 Project and Contributors <https://github.com/PyO3>"
]
description = "Rust bindings of NumPy C-API"
documentation = "https://docs.rs/numpy"
edition = "2018"
rust-version = "1.48"
repository = "https://github.com/PyO3/rust-numpy"
categories = ["api-bindings", "development-tools::ffi", "science"]
keywords = ["python", "numpy", "ffi", "pyo3"]
license = "BSD-2-Clause"

[dependencies]
cfg-if = "1.0"
libc = "0.2"
num-complex = ">= 0.2, <= 0.4"
num-traits = "0.2"
ndarray = ">= 0.13, < 0.16"
pyo3 = { version = "0.15", default-features = false }

[dev-dependencies]
pyo3 = { version = "0.15", features = ["auto-initialize"] }

[features]
default = []
rayon = ["ndarray/rayon"]

[workspace]
members = ["examples/*"]
